dependencies:
  flutter_map: ^5.0.2
  open_street_map: ^1.0.1
  fl_chart: ^3.0.0
  firebase_core: ^2.18.4
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.6.0
  dio: ^5.3.4
  geolocator: ^20.0.2
  flutter_local_notifications: ^9.2.0+10
  provider: ^6.0.2